modLoader="javafml"
loaderVersion="[41,)"
license="GPL-3.0 License"
issueTrackerURL="https://github.com/KiwiOfLesbos/MiniCoal/issues"

[[mods]]
modId="minicoal"
version="1.19-1.0.0"
displayName="MiniCoal"
logoFile=""
logoBlue=false
credits="Thanks to all the snails in my backyard."
authors="KiwiOfLesbos"
description="Mini Coal & Charcoal"

[[dependencies.minicoal]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.minicoal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
